version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user --upgrade pip neuromation
            pip install --user -r .circleci/requirements.txt
      - run:
          name: Build Image
          command: |
            neuro config login-with-token $NEURO_TOKEN
            neuro config show

            make -f test.mk _generate_random_label_32 > /tmp/test-id.txt

            neuro run -s cpu-small --tag "test-id:`cat /tmp/test-id.txt`" neuromation/base sleep 3h
      - run:
          name: Kill jobs left
          command: |
            export JOBS_LEFT=$(neuro -q ps --tag "test-id:`cat /tmp/test-id.txt`")
            [ ! "$JOBS_LEFT" ] || neuro kill $JOBS_LEFT
          when: always

      - docker/check
      - docker/push:
          image: neuromation/ml-recipe-mountain-car
          tag: debug


workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: CHANGEME
            tags:
              only:
                - /.*/
